### ISSUE TITLE
Add source from Statistics Canada

### ISSUE THREAD

**Issue by charphi** [nbbrd/sdmx-dl#165]
API documentation: https://www.statcan.gc.ca/en/developers/wds

SdmxWebSource:

| Key | Value |
| --- | --- |
| Name | STATCAN |
| Description | Statistics Canada |
| Aliases | |
| Driver | |
| Dialect | |
| Endpoint | https://www150.statcan.gc.ca/t1/wds/rest |
| Properties | |
| Website | https://www150.statcan.gc.ca/n1/en/type/data?MM=1 |
| Monitor | |

Problems:
- doesn't follow standard REST API
- stores frequency in an annotation instead of dimension or attribute

**Comment by charphi** [comment]
Done in fb459750f878b6674fc5e84ceff5fc8a64a1349b

**Comment by CyLuGh** [comment]
Seems like there are still some troubles with the source:

`sdmx-dl list concepts STATCAN 'StatCan:DF_10100139(1.0)'` will throw an IOException: Invalid series key '.'

`sdmx-dl fetch data STATCAN 'StatCan:DF_10100002(1.0)' '1.1'` does have some null data... and I wonder if the symbol used is not yet again something else (might be caused by my recent update to .net 6), I'll have to check.

**Comment by charphi** [comment]
So, after verification, there are three distinct problems
- The command-line parsing of single quote doesn't work as expected
- StatCanDriver doesn't validate its DataflowRef input
- Data parsing is failing due to a misssing key
